pipeline {
    agent any

    environment {
        // Change build server IP acccording to your AWS EC2 Build server Private Ip
        BUILD_SERVER_IP = '172.31.4.138'
    }

    stages {
        stage('Cleanup and Clone Repository') {
            steps {
                script {
                    // Remove existing Day6 directory and clone the latest repo
                    sh "ssh ubuntu@${BUILD_SERVER_IP} 'sudo rm -rf /home/ubuntu/SSL_devops* && git clone https://github.com/krishna1369/SSL_devops.git /home/ubuntu/SSL_devops'"
                }
            }
        }

        stage('Build Docker images on Build Server') {
            steps {
                script {
                    // Execute Ansible playbook on Build Server
                    sh "ssh ubuntu@${BUILD_SERVER_IP} 'ansible-playbook /home/ubuntu/SSL_devops/Ansible/build.yaml'"
                }
            }
        }

        stage('Deploy Script on Deploy Server') {
            steps {
                script {
                    // Execute deployment playbook on Deploy Server
                    sh "ssh ubuntu@${BUILD_SERVER_IP} 'ansible-playbook /home/ubuntu/SSL_devops/Ansible/deploy.yaml'"
                }
            }
        }
    }
}
